name: Build RPMs

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  OS_VERSION: 4.5.0.16
  MCE_VERSION: 1.115.4
  MCE_RELEASE: 1.14.3.jolla

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build mce
    strategy:
      matrix:
        arch: ['aarch64', 'i486']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone mce
        uses: actions/checkout@v3
        with:
          repository: sailfishos/mce
          ref: ${{ env.MCE_VERSION }}
          path: mce
          clean: false
          submodules: recursive

      - name: Copy patches
        run: |
          cp *.patch mce
          cp -r flashlight-patch mce

      - name: Patch
        working-directory: mce
        run: |
          patch < assistantButton.patch
          cd rpm
          patch < ../spec.patch
          sed -i "s/{{{releaseName}}}/$MCE_RELEASE/g" mce.spec

      - name: Prepare
        working-directory: mce
        run: docker pull coderus/sailfishos-platform-sdk:$OS_VERSION && mkdir output

      - name: Build ${{ matrix.arch }}
        working-directory: mce
        run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$OS_VERSION /bin/bash -c "
          mkdir -p build ;
          cd build ;
          cp -r /share/* . ;
          mb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} build ;
          sudo cp -r RPMS/*.rpm /share/output"

      - name: Upload RPM (${{ matrix.arch }})
        uses: actions/upload-artifact@v3
        with:
          name: rpm-${{ matrix.arch }}
          path: mce/output
